### ISSUE TITLE
🧪 Stabilize file snapshot tests

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#14253]
### 🧪 Tests

We recently added a test for file snapshots. However, it does not seem to be stable.

### 🕵️ Details

It looks like dates being generated for experiences are not stable and can drift dramatically.

SEE:

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/16568664211/job/46854876161

### 🙋‍♀️ Proposed Solution

We already set `$faker->seed(0)` so it could be somewhere else where the randomness is being introduced. Currently, I am not certain where this may be.

It might even be that a PR merged that affected this shortly after the snapshot was introduced and therefore was not failinfg so the base snapshot was not updated? 

#### State?

I think another good solution could be to add a `snapshot` state method that creates highly deterministic results from the factories.

```php
public function snapshot()
{
    return $this->state([
        'start_date' => '2020-01-01',
        'end_date' => '2050-01-01',
        'type' => EducationType::BACHELORS_DEGREE->name,
    ]);
}
```

### ✅ Acceptance Criteria

- [ ] Snapshot tests are stable

**Comment by petertgiles** [comment]
This was solved in a PR already

**Comment by esizer** [comment]
Looks like it was not solved. Something in the `EducationExperienceFactory` is still causing diffs in the application snapshot.

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/16647345438/job/47111097500
